services:
  - type: web
    name: lysandra-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: AES_KEY_B64
        sync: false
      - key: HMAC_SECRET
        sync: false
      - key: EXPECTED_APK_CERT_SHA256
        sync: false
      - key: ALLOWED_PACKAGE_NAMES
        value: com.drdev.hamza
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_DB_URL
        sync: false
      - key: ADMIN_RELOAD_TOKEN
        sync: false
      - key: ADMIN_PANEL_ORIGINS
        sync: false
