"""
POST /api/v1/fetch -- the core endpoint. The Android app sends an AES-GCM
encrypted URL + request signature; this verifies everything, decrypts,
routes to the right extractor, logs the event, and returns video info.
"""
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from app.extractors import get_extractor
from app.extractors.base import ExtractionError
from app.firebase_client import config_cache
from app.security import decrypt_payload, verify_app_identity, verify_signed_request
from app.utils.logging_util import log_blocked_domain_hit, log_device_seen, log_fetch_event
from app.utils.url_safety import UnsafeUrlError, normalize_and_validate

router = APIRouter()


class FetchRequest(BaseModel):
    payload: str          # base64 AES-GCM encrypted URL
    device_id: str        # stable per-install id generated by the app


@router.post("/api/v1/fetch")
async def fetch_video(payload: FetchRequest, request: Request):
    body_raw = await request.body()
    verify_signed_request(request, body_raw)
    verify_app_identity(request)

    client_ip = request.headers.get("X-Forwarded-For", request.client.host).split(",")[0].strip()
    log_device_seen(payload.device_id, client_ip)

    real_url = decrypt_payload(payload.payload)

    try:
        normalized_url, domain = normalize_and_validate(real_url)
    except UnsafeUrlError as e:
        raise HTTPException(400, f"Invalid URL: {e}")

    blocked = config_cache.get("blocked_domains", {}) or {}
    if domain in blocked:
        log_blocked_domain_hit(payload.device_id, client_ip, domain)
        raise HTTPException(
            451,
            detail={"blocked": True, "message_html": blocked[domain].get("message_html", "This domain is currently unsupported.")},
        )

    extractor = get_extractor(domain)
    try:
        info = await extractor.extract(normalized_url)
    except ExtractionError as e:
        log_fetch_event(payload.device_id, client_ip, domain, extractor.name, False, e.message)
        raise HTTPException(422, detail={"message": e.message, "code": e.code})
    except Exception as e:
        log_fetch_event(payload.device_id, client_ip, domain, extractor.name, False, str(e))
        raise HTTPException(500, "Unexpected extraction error")

    log_fetch_event(payload.device_id, client_ip, domain, extractor.name, True)
    return info.model_dump()
